name: Publish Library

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@michaelcabanacirclek'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test package
        run: npm run test
        
      - name: Build package
        run: npm run build
        
      - name: Publish to npm
        working-directory: dist
        run: npm publish